# Generated by Django 3.0.2 on 2020-01-09 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='content',
            new_name='description',
        ),
    ]
